const artists = [
    {name: "Amias Hanley ",        
            image: "assets/amias.png", 
            title: "Her Noise Floor: Selection, Extraction, Exclusion", 
            description: " The noise floor is considered to be the sum of all unwanted signals in an audio recording. That is the air conditioner, a bird’s song, a police siren or a child crying—depending on where you’re listening from. A recording’s noise floor can be influenced by the material spatial properties of a room or an environment, and it can also be self-generated by the thermal agitation of electrons that make up the circuitry (containing rare earth elements) of a recording device or microphone. In this sense, we might think of the noise floor as the result of millions of years of geologic formation. <br> <br> <i>Her Noise Floor: Selection, Extraction, Exclusion </i> (HNF) is a practice-based research project that responds to digital audio material that is housed within the <i>Her Noise Archiveat</i> UAL Archives and Special Collections Centre—asking, what can the noise floor in these archived recordings tell us about the histories, social relations, climate, and economic and geopolitical context in which the<i> Her Noise</i> (2005) exhibition originated? <br><br>Through the framework of critical data studies, extractivism, and auditory technoculture, HNF aims to situate the noise floor as a highly localised, non-neutral, audible ecological material. Here, the noise floor is explored as both an archive of the in-situ acoustic properties of the rooms and places where these recordings were made and as a cartography of the geosocial conditions and curatorial decisions that produced the <i>Her Noise</i> (2005) exhibition. <br> <br><i>HNF</i> consists of two interrelated, process-driven parts: Firstly, a machine learning model was trained on audio datasets from Melanie Clifford's radio program, <i>Her Noise Series</i>, broadcast on Resonance FM in 2005. This model classifies whether an audio file is ‘noise’ or ‘signal’. Second, is the browser-based <i>HNF Interactive Noise Map</i>, which functions as an experimental archive and compositional tool, allowing listeners to listen to engage with predictions made by the model and explore the noise floor as ecological material. <br> <br>In navigating the <i>HNF Interactive Noise Map</i>, I hope that listeners may actively explore the noise floor as ecological material, as a ‘tangled cartography’ (Hilde Neset, 2007)that holds traces of global techno-political structures and climate systems and acts as a contemporary continuation of <i>Her Noise Archive</i>. The <i>HNF</i> Interactive Noise Map aims to pay homage to the mapping processes used by curators Lina Dzuverovic and Anne Hilde Neset, at the inception of Her Noise (2005), and provide a place to reimagine, rearrange, and relisten to the material conditions of the past through emergent auditory technocultures. <br><br>For more on this project see: Her Noise Floor: Selection, Extraction, Exclusion <br><br>Hilde Neset, A. 2007. <i>A Tangled Cartography; The Mapping of Her Noise.</i> Available at:  https://hernoise.org/tangled-cartography/",
            instagram: "amias_hanley"},
    // {name: "Yilin Ma", 
    //         image: "No Image", 
    //         title: "Untitled", 
    //         description: "No Description" },
    {name: "Claudia Gudin",        
            image: "assets/claudia.png", 
            title: "Pearl System", 
            description: "The Pearl System investigates the possibilities of transformation in space, to understand which are the means to explore for having new approaches. How can we escape from the inherited infrastructures of imagination? How do we experience space? I intend to create a piece which will take action on these questions. Pointing at the structural and behavioural systems, aiming to re-articulate our understanding about space.The piece intends to encourage the activity of going through the curtain to access the space behind it, by making the audience interact with the installation and at the same time including their action as part of the piece. The chosen material is the one that offers the installation sonorous possibilities. Pearls are a material highly related to luxury, to the delicate and feminine, by displacing them and placing them in this other context, this new functionality appears in them. Generating this space, similar to a 'playground', where the pearls are detached from their rigidity and seriousness, enables us to incorporate in them a more vivid and liberated aspect. Furthermore, this aims to investigate the extent of the deconstructive capacities in the artistic installation and the possibilities offered by the sound and the materials chosen.",
            instagram: "1313.es"},
    {name: "Linlin Zhang",         
            image: "assets/linlin.png", 
            title: "Bag Piece", 
            description: "What happens when you expose your vulnerability in public? After further research, I observed the gradual disappearance of homeless women from society. I found that the majority of them are seen as 'hidden figures' who face constant and unpredictable threats. To shed light on this social phenomenon, I created a performance piece. This performance aims to explore the interplay between power and sexuality, as well as the implications of vulnerability when presenting oneself as an individual without gender advantage and social status. Through the performance, in which I enter a sealed plastic bag and place myself in a state of near suffocation, the audience's response will serve as a test: will they choose to help or ignore? This is the answer I hope to uncover through this collaborative performance art piece with the audience.",
            instagram: "llnowater" },
    {name: "Millie Watson",       
            image: "assets/millie.png", 
            title: "Cubicle Confessional", 
            description: "<i>Cubicle Confessional</i> is: <p class='indented-text'> a performance, </p> <p class='indented-text two'> a joke, </p> <p class='indented-text three'> a ritual, </p> <p class='indented-text four'> an incident, </p> <p class='indented-text five'> an opportunity to re-engage with our  </p> <p class='indented-text six'> ‘engaged’ spaces. </p> <p id='content'>Inspired by the community focus and participatory thread that ran through the work at the 2005 Her Noise exhibition, <i>Cubicle Confessional</i> invites the ‘audience’ to enjoy a moment of levity in a public place we desperately try to keep private. <br><br> <b>Come to the toilets by the kit room </b> and make your vocal offering to the hand dryer – invigilator of this sonic environment whose streaming voice penetrates silence and envelopes the spectrum.</p>",
            instagram: "milliewatsonmusic" },
    {name: "Da Won Kwack",         
            image: "assets/dawon.png",
            title: "R U Femi?", 
            description: "<i>R U FEMI?</i> (2024) identifies the roots of misogyny stemming from hate speech and accuses urgent issues such as femicide and gender violence in Korea. Inspired by socialist feminism, the foundational point for <i>Her Noise Archive</i> (2012), it intends to critique the side effects of patriarchy and capitalist structures. This sound installation commences with the question, 'Are you femi(nist)?', a phrase deemed as hate speech in Korea. It deals with the victims who have short hair a symbol of feminism- and those who get victimised simply for being women. <br><br>The symbolic representation of victims manifests through the sounds emitted by decaying fruits, regarded as a female archetype. These sounds convey the hate speech caused by misogyny, the sound related to the events of victims of gender violence and femicide. Furthermore, it is designed to highlight decay in the envelope to underscore the potential for energy to sustain or rise rather than diminish.<br><br> Invite the audience to empathise with the victim's suffering or express their emotions while interacting with the rotten fruits, according to the provided text score. Their improvisation will vary depending on how the audience engages with pain from a tragic event.",
            instagram: "jolitea"},
    {name: "VenAur",               
            image: "assets/venaur.png", 
            title: "Where are you <i>Really</i> From?", 
            name:"VenAur", 
            description: "The exploration of the common question, “Where are you really from?” was inspired by the conceptual structure of the <i>Her Noise Archive</i>. Irene Revell (2023) emphasized that the archive isn't just associated with “feminism”, but encompasses a broader theme of “power.” It’s designed to provoke power imbalances and explore the ways individuals can interrogate power relations and dynamics. The question itself, “where are you really from?,” holds a higher significance within this context, exploring how power dynamics not only dictate who poses the question but also influences who becomes the subject of these inquiries. <br><br>For this project, I conducted four interviews, myself included. Each individual was either a transracial adoptee or someone with a diverse background. Some of the questions I posed included:<br>- How have you dealt with or responded to stereotypes and racism?<br>- Have you struggled with belonging?<br>- How would you imagine a future where questions like, “where are you really from?” may no longer be asked?<br><br>Towards the end of the interviews, participants shared suggestions for more considerate ways to ask questions:<br>- What is your ethnicity?<br>- What is your background/heritage?<br> - What languages do you speak?",
            instagram: "venaurt"},
    {name: "Jiali Yang",           
            image: "assets/jiali.png", 
            title: "The Moss", 
            description: "Intuitively, the idea that touching nature can cross interspecies boundaries makes sense. And could there be a better example of the existence of touch in the plant kingdom than the mosses and their relatives, the moss? It doesn't hurt us, has no venom or hard shell. Nor does it take hardly anything from the hosts it touches: mosses are not parasites. However, it softens trees, prevents soil erosion, and provides shelter for tiny creatures that we hardly notice. We often gaze at the trees and listen to the wind, moss may not give you such an intuitive feeling, it doesn't bring you the immediate shock that giant trees and flowers do, and even if they look so lovely or marvellous, we don't stop for it for long. The word touch comes from the Old French word 'toche' - meaning to strike, or even assault. Touch is a kind of forcible prying. So touch itself has a violent color, that is, a sense of aggression, we can gently touch it, or we can violently destroy it, it all depends on our heartfelt thoughts. So touching the moss can also be seen as a way to open the inner link with nature, when you are ready to touch it, you can feel it is accepting, inclusive. Unlike skin-to-skin contact with humans, you don't need any pressure, but it gives you a constant energy feedback.",
            instagram: "arwen2559" },
    {name: "Ethan Cohen",          
            image: "assets/blank.png", 
            title: "Sports News Blues",
            description: "<i<Sports News Blues </i>is a video installation and performance piece that reimagines the rhythms, myths, and textures of contemporary football culture." },
    // {name: "Jiachen Li", 
    //         image: "No Image", 
    //         title: "Untitled", 
    //         description: "No Description" },
    {name: " Marina Sanchez",      
            image: "assets/marina.png", 
            title: "Can Tree-O Air", 
            description: "Can Tree-O Air is a response to the Her Noise archive, a work that considers the listening process through exploring the relationship between microphones and speakers using tree sounds and feedback. The starting point for this work grew out of gratitude for the air that is available to humans and non-humans. Humans and trees are interdependent whereby the tree expels oxygen and captures carbon dioxide, and the human breathes out carbon dioxide and breathes in oxygen. Transposing from the work of Maria Puig de la Bellacasa (2017), if I imagine the trees’s work as caring for me,  might I listen to the tree differently?Listening after Nature (Wright, 2022) offers a way of listening giving permission and space to rethink what is heard, to keep in mind the relationship between the recordist and field, and to consider entanglement of non-human and human, to ask repeatedly what is it that I am not hearing. Play back in “else-where places” offers the opportunity to think further ”what am I not hearing” in this recording, (Wright,2022, p.153). The acousmatic nature of the tree sounds 'defamilarises our perceptions' asking us to 'listen again' (LaBelle, 2018). The relationship between loudspeakers and microphones mediated by material, space and movement, illustrates how the composition heard will differ depending on the space. In this sense there is a certain fragility to the sounds produced as the performer listens and searches for sounds uniquely constructed by relations between the different influences in the space. Maybe in this sense, the work does address agency by acknowledging the inter-relational effect of all actors in the field, including the tree sounds whilst also imagining new perceptions and relations. <br> <br> De La Bellacasa, M, P. (2017). Matters of care: Speculative ethics in more than human worlds. Minneapolis, University of Minnesota Press. <br> LaBelle, B. (2018) Sonic agency, sound and emergent forms of resistance. London: Goldsmith’s Press. <br> Wright, M, P. (2022). Listening after nature. New York: Bloomsbury Academic." },
    // {name: "Ni Jia",               
    //         image: "No Image", 
    //         title: "Untitled", 
    //         description: "No Description" },
];

const navbar = document.getElementById("navbar");
const content = document.getElementById("content");
const overlay = document.getElementById("overlay");
const bgImg = document.getElementById("bg-img");
const performancesTitle = document.getElementById("performances");
const performancesListContainer = document.getElementById("performances-list");
const performancesData = [
    { name: "Amias Hanley & VenAur", title: "Her Noise Floor", time: "17:30", location: "Atrium, LCC" },
    { name: "Ethan Cohen", title: "Sports News Blues", time: "17:45", location: "Atrium, LCC" },
    { name: "Marina Sanchez", title: "Can Tree-O Air", time: "18:00", location: "Atrium, LCC" },

];

//-------Navbar------
let navbarVisible = false; // navbar visibility
navbar.style.pointerEvents = "none";

//----bg img----
function setBackgroundImage() {
    const screenWidth = window.innerWidth;

    if (screenWidth <= 1079) {
        bgImg.style.backgroundImage = 'url("bg-img-mobile.png")';
    } else {
        bgImg.style.backgroundImage = 'url("bg-img.png")';
    }
}

bgImg.style.display = "block";

///------------ toggle the navigation menu---
function toggleMenu() {
    //not visible
    if (!navbarVisible) {
        displayArtistNames(); 
        content.classList.add("blur"); 
        bgImg.classList.add("blur");
        navbar.style.pointerEvents = "auto"; 
    } else {
        content.classList.remove("blur");
        bgImg.classList.remove("blur"); 
        navbar.style.pointerEvents = "none"; 
    }
    navbarVisible = !navbarVisible; 
    navbar.style.opacity = navbarVisible ? "1" : "0"; 
    overlay.style.display = navbarVisible ? "block" : "none"; 
}

//------ display artist names-----
function displayArtistNames() {
    const artistList = document.getElementById("artist-list");
    artistList.innerHTML = ""; // Clear previous list items

    artists.forEach((artist, index) => {
        const listItem = document.createElement("li");
        listItem.textContent = artist.name;
        listItem.onclick = () => showArtist(index);
        artistList.appendChild(listItem);
    });
}

// ---display artist details----
function showArtist(index) {
    const artist = artists[index];
    bgImg.style.display = "none";

    document.body.style.backgroundImage = 'none';

    const instagramLink = artist.instagram
    ? `<a href="https://www.instagram.com/${artist.instagram}" target="_blank" class="instagram-link">
           <img src="instagram.png" alt="Instagram" class="instagram-icon">
           <span class="instagram-username">${artist.instagram}</span>
       </a>`
    : '';

    content.innerHTML = `
        <img src="${artist.image}" alt="${artist.name}">
        <h2>${artist.title}</h2>
        <h3>${artist.name}</h3>
        <p>${artist.description}</p>
        <div>${instagramLink}</div>
      
    `;
    toggleMenu(); 
}


function displayPerformances() {
    // Clear previous contents---
    performancesListContainer.innerHTML = "";

    // ----Create list items for each performance---
    performancesData.forEach((performance) => {
        const performanceItem = document.createElement("div");
        performanceItem.classList.add("performance-item");
        performanceItem.innerHTML = `
            <div><strong>${performance.name}</strong></div>
            <div><em>${performance.title}</em></div>
            <div><span>Time: ${performance.time}</span></div>
            <div><span>Location: ${performance.location}</span></div>
        `;
        performancesListContainer.appendChild(performanceItem);
    });

    performancesListContainer.style.display = "block";
}

// call functions
displayPerformances();
displayArtistNames();
setBackgroundImage();
window.addEventListener('resize', setBackgroundImage);